### ISSUE TITLE
encode psi4 best practices 

### ISSUE THREAD

**Issue by vtlim** [vtlim/off_psi4#16]
- [SCF](http://www.psicode.org/psi4manual/master/scf.html#recommendations)
- [DFT](http://www.psicode.org/psi4manual/master/dft.html#recommendations)
- [DFMP2](http://www.psicode.org/psi4manual/master/dfmp2.html#recommendations)

**Comment by dgasmith** [comment]
Consider using the JSON interface to avoid reading/write ASCII text. See [here](https://github.com/psi4/psi4/blob/master/tests/json/schema-1-gradient/input.py) and [here](https://molssi-qc-schema.readthedocs.io/en/latest/spec_components.html).

**Comment by vtlim** [comment]
Thanks @dgasmith. The original code was written two years ago so I haven’t taken the time to implement the JSON interface yet but do hope to...
