### ISSUE TITLE
read SCS-MP2 energy

### ISSUE THREAD

**Issue by vtlim** [vtlim/off_psi4#24]
These are already printed in normal MP2 calculations.

**Comment by dgasmith** [comment]
See #16, I would not recommend parsing Psi4.

**Comment by vtlim** [comment]
code here: 48ca256dce69f32c8a61b735e53ea746e3af115c
still needs tests

**Comment by vtlim** [comment]
tests in commits: 17251f7b0ceea4facd494eff8085fae7da42bba6, 09f871fe83ab1cb1255640fc9ec01ca815ce598d
