### ISSUE TITLE
CMS Cookiecutter

### ISSUE THREAD

**Issue by dgasmith** [vtlim/off_psi4#25]
You might want to consider the best practices and layouts found in this cookie cutter: https://github.com/MolSSI/cookiecutter-cms

It would be very good to get CI running on this software.

**Comment by vtlim** [comment]
I do have CI! As of a week or so ago, but haven’t put the badge on yet, nor is the coverage very extensive. @bannanc and I were talking about whether it would make sense to move the code into cookie cutter or add what else may be missing.

**Comment by vtlim** [comment]
Moved with cookecutter into https://github.com/MobleyLab/quanformer
