### ISSUE TITLE
PEP8 formatting

### ISSUE THREAD

**Issue by vtlim** [vtlim/off_psi4#8]
https://github.com/google/yapf

**Comment by dgasmith** [comment]
Onto of PEP formatting you might want to consider `snake_case` over `camelCase` as found in the majority of Python packages.

**Comment by vtlim** [comment]
*main*

- [ ] avgTimeEne.py
- [ ] confs2turb.py
- [ ] confs_to_psi.py
- [ ] diffSpeOpt.py
- [ ] executor.py
- [ ] filterConfs.py
- [ ] get_psi_results.py
- [ ] getTurbResults.py
- [ ] initialize_confs.py
- [ ] matchMinima.py
- [ ] match_plot.py
- [ ] plotTimes.py
- [ ] procTags.py
- [ ] quan2modsem.py
- [ ] stitch_spe.py

*data_tests*

- [ ] helper.py
- [ ] test_confs_to_psi.py
- [ ] test_filterConfs.py
- [ ] test_get_psi_results.py
- [ ] test_getTurbResults.py
- [ ] test_procTags.py
- [ ] test_smi2confs.py
- [ ]

**Comment by vtlim** [comment]
Addressed by 5dc462ecceebca8b528ceefd74b5a5b61caaee07
